modified models with jpa
Anoromi/cult-of-tim pull request #5
Opened 2023-10-03 19:53 UTC by Kasgor

added changes to all models

2023-10-04 07:33 UTC, Anoromi commented on src/main/java/com/example/cult_of_tim/cultoftim/models/Book.java
>      private String title;
Варто додати макимальний розмір.

2023-10-04 07:33 UTC, Anoromi commented on src/main/java/com/example/cult_of_tim/cultoftim/models/Category.java
>      private String name;
Розмір

2023-10-04 07:33 UTC, Anoromi commented on src/main/java/com/example/cult_of_tim/cultoftim/models/Promotion.java
> +    private List<User> users;
До чого у Promotion з'єднання до користувачів?

2023-10-05 11:11 UTC, HoWurk commented on cult-of-tim-auth/src/main/java/com/cult_of_tim/auth/cultoftimauth/repositories/UserRepository.java
> +    void deleteById(UUID id);
Most of these methods exist in jparepository and don't need to be duplicated:
![image](https://github.com/Anoromi/cult-of-tim/assets/84322415/f678cbcb-7892-4807-be7b-5b37bc02bd7d)
![image](https://github.com/Anoromi/cult-of-tim/assets/84322415/67674819-6ee0-4ef6-8e2d-9f6ee86bcc05)
etc
Other Repository files, same thing

2023-10-05 11:11 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/service/impl/PromotionMockService.java
>      }
We receive not an entity here, need to change to PromotionCreationDTO or similar stuff
https://www.baeldung.com/java-dto-pattern

2023-10-05 11:11 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/service/impl/PromotionMockService.java
> +        return promotionRepository.save(updatedPromotion);
same as create, need possibly update dto

2023-10-05 11:11 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/models/Author.java
> +    private List<Book> books;
Either make author contain books, or books contain authors. One of the two.
Same with categories and books.

2023-10-05 11:11 UTC, HoWurk commented on cult-of-tim-auth/src/main/java/com/cult_of_tim/auth/cultoftimauth/dao/UserDao.java
>      Optional<UserToken> getUserTokenFor(UUID token);
If we move on from UserDao, we either change it fully with UserDaoMock and UserMockService so it actually builds, or don't change it, but still fix it.

2023-10-05 12:14 UTC, HoWurk requested changes

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/service/impl/PromotionMockService.java
> +        return promotionRepository.existsByIdAndGlobalPromotion(promotionID, true);
First, change globalPromotion to global (boolean in Promotion).
Second, make method better in PromotionRepository, read comment there.
Third, insert here. If for some reason you need existsbysomething, don't put it in isGlobalMethod.

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/service/PromotionService.java
> +    Promotion updatePromotion(Long id, String description, LocalDateTime startDate, LocalDateTime endDate, List<PromotionDiscount> discounts, boolean globalPromotion);
this is just plain wrong, again, https://www.baeldung.com/java-dto-pattern
Or leave it as it was previously, and ask lecturer next time.

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/repositories/PurchaseRepository.java
> +    //void deleteById(Long id);
why comment and not just delete?

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/repositories/PromotionRepository.java
> +    boolean existsByIdAndGlobalPromotion(Long promotionId, boolean global);
I don't know why this is needed, if you need to check if item exists, then just do boolean existsById, if you need to check if this id has global true,
boolean existsByIdAndGlobalPromotionTrue(Long promotionId);
https://www.baeldung.com/spring-data-derived-queries

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/service/impl/PromotionMockService.java
>          return promotionRepository.save(updatedPromotion);
change it back, or fix it, read in interface comment

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/repositories/PromotionRepository.java
> +    List<Promotion> findByUserId(Long userId);
still doesn't work, no field userId in promotion. if you want to query, @Query

2023-10-05 12:14 UTC, HoWurk commented on src/main/java/com/example/cult_of_tim/cultoftim/repositories/BookRepository.java
> +    List<Book> findByCategoryId(Long categoryId);
still doesnt work, findAllByAuthorsContaining, same with category
no fields authorId, categoryId

2023-10-06 03:13 UTC, HoWurk approved these changes

2023-10-06 06:31 UTC, merged